### ISSUE TITLE
Preact not installed? (Windows)

### ISSUE THREAD

**Issue by ericvrp** [iaincollins/next-auth-example#1]
```
Error: No valid exports main found for 'C:\Users\eric\dev\CopyrightDelta\next-auth-example\node_modules\preact'
    at resolveExportsTarget (internal/modules/cjs/loader.js:618:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:650:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:948:27)
    at Function.Module._load (internal/modules/cjs/loader.js:854:27)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\eric\dev\CopyrightDelta\next-auth-example\node_modules\next-auth\dist\server\pages\signin.js:1:104)
    at Module._compile (internal/modules/cjs/loader.js:1128:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:983:32)
    at Function.Module._load (internal/modules/cjs/loader.js:891:14)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\eric\dev\CopyrightDelta\next-auth-example\node_modules\next-auth\dist\server\pages\index.js:1:215) {
  code: 'MODULE_NOT_FOUND'
}
```

**Comment by iaincollins** [comment]
Huh, that is weird as it's listed as a dependancy, and should be automatically installed.

```
  "dependencies": {
    "nodemailer": "^6.4.6",
    "oauth": "^0.9.15",
    "preact": "^10.4.1",
    "preact-render-to-string": "^5.1.7",
    "querystring": "^0.2.0",
    "typeorm": "^0.2.24"
  },
```

Could you confirm steps to replicate? Thanks!

**Comment by ericvrp** [comment]
I got this
  "dependencies": {
    "next": "^9.4.0",
    "next-auth": "^2.0.0-beta.40",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "sqlite3": "^4.2.0"
  }

**Comment by iaincollins** [comment]
Oh! Yeah if you are checking out the example, then running `npm i` should be enough.

(The dependancies I posted are for next-auth library, so Preact should be pulled in automatically.)

I don't know of any reason why this would happen, but will take a look and try to replicate on Windows in case it's platform specific.

**Comment by ericvrp** [comment]
I do see preact in node_modules

**Comment by ericvrp** [comment]
It gets confusing quickly have two (P)React favorws. Maybe switch next-auth@beta to use whatever nextjs supplies? 

P.S. It does work for me on Linux

**Comment by iaincollins** [comment]
Thanks Eric! I wonder if it's an issue with Preact on Windows or how it's being invoked from NextAuth that it only fails on Windows somehow.

Agree it is confusing for anyone looking under the hood and is one of the things we need to document as I'm sure it will come up again.

**Why it uses Preact**

The reason it uses Preact is that we need to render some web pages on `/api/*` routes, for those who don't want the extra work of creating custom pages - especially when getting it working for the first time.

Unfortunately, API routes in Next.js apps don't have access to React (as pages do), and I didn't want to add the overhead of requiring React to the API route, especially as the pages are so simple. (In theory, no one should ever know or care they are built with Preact.)

This issue will need investing though.

**Comment by iaincollins** [comment]
@ericvrp Doing some investigation; can you confirm what version of Node.js you have on your Windows system? (FYI 12.x or 13.x should work for sure).

**Comment by ericvrp** [comment]
C:\Users\eric\dev\CopyrightDelta\next-auth-example (master -> origin) (next-auth-example@2.0.0-beta)
λ node --version
v13.3.0

**Comment by iaincollins** [comment]
Thanks! I think it might be a Preact issue and I *think* it might be fine with newer versions of v13 but am going to investigate.

**Comment by iaincollins** [comment]
I appreciate Preact creates confusion and potential problems like this, but just remembered another reason for avoiding React being that it would create a dependancy / peerDependancy on it and was concerned that mismatched versions would tie it to a specific version of React, which is also annoying / confusing for everyone (especially as `next-auth` is both a server side component and a client component, and the client component leverages React as a peerDependancy because it supports Hooks).

So, all the options are somewhat terrible. 

I'm hopeful the issue with Preact is a blip with Node.js < 13.8 - which, as an odd versioned release, will not be an LTS release like Node.js 12 is and  Node.js 14 will be; it seems like a other libraries had a problem with earlier releases of Node.js 13.x so Preact wouldn't be alone in that.

If it turns out to be more substantive, could always use string literals and not use Preact I guess; it's just feels like a good tradeoff for not having to context switch from writing React.

**Comment by ericvrp** [comment]
In both node 14.3.0 and 12.6.3 I had issues similar to the one below. Will test with the latest v13 now...

```
> sqlite3@4.2.0 install C:\Users\eric\dev\CopyrightDelta\next-auth-example\node_modules\sqlite3
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@12.16.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
node-pre-gyp WARN Pre-built binaries not installable for sqlite3@4.2.0 and node@12.16.3 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error bad download
gypgyp ERR!  ERR!find Python
find Pythongyp
gyp  ERR! ERR! find Pythonfind Python Python is not set from command line or npm configuration
 Python is not set from command line or npm configuration
gypgyp  ERR!ERR!  find Pythonfind Python Python is not set from environment variable PYTHON
 Python is not set from environment variable PYTHON
```

**Comment by ericvrp** [comment]
node 13.14.0 does the same. I'm sure we could fix the missing Python installation here but reducing the number of dependencies would probably be a better strategy.

**Comment by ericvrp** [comment]
So this is a different error from the original issue with Preact. This has to do with sqlite3. I got the example working with node v14.3.0 (Others with the exception of my original vesion would work to probably) and swapping sqlite with mongodb in the example.

**Comment by iaincollins** [comment]
Thanks @ericvrp!

It seems like Preact doesn't work with earlier 13.x branches, some other popular libraries like Rollup had issues with that too, which is probably to be expected for an odd versioned release, especially with all the changes to module handling in Node.js over the last year or so.

That's interesting feedback RE: sqlite 

It has a fairly hefty build process, but I didn't realise it actually required Python. I agree that's quite a burden for Windows users. That is a good case for swapping out the default example for something else.

I would ideally like the example to use JWT token when that support is in, - and a simple callback that lets people write their own function to get / save user data. This would need no other dependancies, but I'm not sure exactly what the auth flow would be like for that yet.

**Comment by iaincollins** [comment]
Closing this off as multiple databases now supported.

When JWT support drops will remove SQLite as a dependency from the example.
