### ISSUE TITLE
Apple Sign in Branch

### ISSUE THREAD

**Issue by geraldnolan** [iaincollins/next-auth-example#10]
I am placing this here for future enhancements to the apple provider documentation.  I again messed up, creating the Team and KeyID.  After the second or third time, I discovered **AuthKey** File downloaded from Apple has the Key in the name of the file.
 
### Faq

- **(node:52500) UnhandledPromiseRejectionWarning: Error: error:0909006C:PEM routines:get_name:no start line**

The **\n** created to make the private key a single line caused the error.  

**Fix:**  
```jsx 
privateKey: process.env.APPLE_PRIVATE_KEY.replace(/\\n/g, '\n'),
```

- **OAUTH_GET_ACCESS_TOKEN_ERROR**

**Fix:**
Make sure to double check that you have both the **TeamID** (Top right hand corner of the apple developer website) and **KeyID** (Located on the file download) in your env variables set correctly.  You will be able to sign in most of the way until after sign-in. The error will throw, causing the server to crash.

**Comment by iaincollins** [comment]
The provider now now handles turning `\\n` back into `\n` automagically if present, so should be a problem.

I'm having some problems with the Apple provider on the example site, but the same details work locally (and I've double checked them); I might need to re-test v3 beta locally and potentially add better logging as I'm not seeing any errors in the console - it's just sending me to the error page for OAuth errors on sign in (at least that behaviour is working!).

**Comment by geraldnolan** [comment]
@iaincollins I did some testing on v3 branch it looks like its throwing this error.

```
[next-auth][error][callback_oauth_error]
Invalid state returned from oAuth provider.
```

Setting the 

```jsx
useState: false 
```
on the provider fixes it.  I'm not sure if that is what we want to do.

**Comment by iaincollins** [comment]
Oh you are good! :D Thank you for looking at this, you've nailed it.

That option is 100% fine to set on a per-provider basis. 

I wondered about that behaviour being an issue but hadn't gotten around to trying it. I should have seen that error on Vercel but it wasn't logged so thought it was probably something else, sometimes I think the logging on Vercel is funky...

Checking state one of the new features for security in v3 (that I'm not sure is full documented yet?) which most providers seem to be fine with but I made it an option in case not all OAuth 2.0 providers supported it (as it's only RECOMMENDED in the RFC and is not listed as MUST).

Like PKCE, it actually seems redundant from a security perspective in our context, but it seemed better to implement the RFC more completely than to have explain that repeatedly.

**Comment by iaincollins** [comment]
@geraldnolan I've made the change in the provider (and refactored the option name I'd used to `state` to fit in with convention used for other options - for better or worse) and is working perfectly on https://next-auth-example.now.sh as of `next-auth@3.0.0-beta.15` \o/

**Comment by geraldnolan** [comment]
@iaincollins nooicce :) That was satisfying to sign into next auth example.
