### ISSUE TITLE
JWT flow doesn't working

### ISSUE THREAD

**Issue by lavcraft** [iaincollins/next-auth-example#13]
Hello, thank you for your work. I'm appreciate you for this project. It's really useful project with good code :)

I'm trying use example without database (with custom Provider, Azure). But after signin - no errors, no warnings and not authentication are :(

I guess, it should works. According to next code in [...nextauth].js
```    // Use JSON Web Tokens for session instead of database sessions.
    // This option can be used with or without a database for users/accounts.
    // Note: `jwt` is automatically set to `true` if no database is specified.
    jwt: true,
```
How to debug this problem?

**Comment by iaincollins** [comment]
Have you tried using the `debug: true` option?

If you can share the provider code I'm happy to take a look at it!

**Comment by lavcraft** [comment]
Yes, i'm using debug: true option. Today i have found problem. cookie with jwt is too long and can't set after call /api/session May be add some checks for cookie length?

**Comment by iaincollins** [comment]
Yah I think we might do something that at some point.

It's tricky because it's a browser limit as well as a per cookie limit and we don't know what other cookies might be getting set.

I think we will add a warning in the relevant section of the docs about this.
